### ISSUE TITLE
Corrupt user object after logging in and out (using Core Data)

### ISSUE THREAD

**Issue by Dev1an** [martijnwalraven/meteor-ios#23]
When I was developing an application using your library, I stumbled upon a problem where the object representing the current logged in user became corrupt. I noticed that after logging out and then logging in again, the relations to the currently logged in user suddenly disappeared. 

When I was trying to solve the problem I saw that it also appeared in your todos example project. Here is a reproduction of the problem using your own todos app:

1. Go to [meteor-ios-todos.meteor.com](http://meteor-ios-todos.meteor.com/) and make sure you have an account on the website
2. Run the todos example project in the iOS simulator and do the following steps inside the running iOS app
3. Log in to your account
- Create a new list and open it
- Mark your list as private
- Add one or more todo items
- Go back to the overview and log out
- Log in again to the same account
- Open your newly created private list
- Notice that your todo item(s) from step 6 are gone

Can you help me solve this problem?

**Comment by martijnwalraven** [comment]
Thanks for reporting this. I looked into it, and it seems this is due to the way inverse relationships are handled in METIncrementalStore. When a referenced object is deleted and added again (as happens when you log out and back in), a referencing object that contains a relationship field (e.g. List.userId or Todo.listId) is not marked as updated. I'll try to get a fix in for this tomorrow.
