### ISSUE TITLE
Saves to server but not core data

### ISSUE THREAD

**Issue by trevorbroad** [martijnwalraven/meteor-ios#3]
Hey again, when I try to save some data, it crashes at runtime on the second line below (let round = ...) , with no real messaging on what is wrong:
```swift
        let managedObjectContext = Meteor.mainQueueManagedObjectContext        
        let round = NSEntityDescription.insertNewObjectForEntityForName("Round", inManagedObjectContext:managedObjectContext) as Round
        round.courseId = "1"
        
        var error: NSError?
        if !managedObjectContext.save(&error) {
            println("Encountered error saving objects: \(error)")
        }
```
If I try instead to save via the following, it saves to the server, but not to core data:
```swift
        let managedObjectContext = Meteor.mainQueueManagedObjectContext
        let fetchRequest = NSFetchRequest(entityName: "Round")
        
        var error: NSError?
        let fetchedResults = managedObjectContext.executeFetchRequest(fetchRequest, error: &error) as [NSManagedObject]?
       
        if let results = fetchedResults {
            results[0].setValue("Red", forKeyPath: "tees")
            
            var error: NSError?
            if !managedObjectContext.save(&error) {
                println("Could not save \(error), \(error?.userInfo)")
            }
            
        } else {
            println("Could not fetch \(error), \(error!.userInfo)")
        }
```

**Comment by martijnwalraven** [comment]
That crash is probably due to the unconditional cast (`as Round`). This isn't specific to Meteor but is a common issue when working with Core Data. It usually means the managed object model hasn't been configured correctly. Make sure you include the module name if you're mapping to a Swift class (see image).

![screen shot 2015-01-21 at 08 16 17](https://cloud.githubusercontent.com/assets/54485/5832456/e5cd2906-a145-11e4-8f9b-4a94dbf49ce7.png)

**Comment by trevorbroad** [comment]
Thanks, you were on the right track. In the end, I had to add the following above the Round class to stop it from crashing.

````swift
@objc(Round)

```` 

The problem remains though, the first snippet above now saves to meteor, but still doesn't save to core data. Any other ideas?

**Comment by trevorbroad** [comment]
I got it working without resorting to @objc(Round) using your first solution. Still no luck getting data to save to Core Data though

**Comment by martijnwalraven** [comment]
Good to hear that worked. What do you mean exactly by not saving to Core Data? If the change happens on the server, saving seems to be working. Do you mean the UI doesn't update? Do you use `NSFetchedResultsController` or manual observing to respond to updates?

**Comment by trevorbroad** [comment]
How can I insert a new managed object into an existing managed object as a subobject using your implementation, and have it map correctly to the meteor collection? For example...

````swift
let round = NSEntityDescription.insertNewObjectForEntityForName("Round", inManagedObjectContext: self.managedObjectContext) as Round
round.name = "foo"

let subObject = NSEntityDescription.insertNewObjectForEntityForName("subObject", inManagedObjectContext: self.managedObjectContext) as SubObject
subObject.name = "bar"

round.sub = subObject
````

````javascript
{
 name: "foo",

 sub: {
  name: "bar"
 }
}
````

**Comment by martijnwalraven** [comment]
There is no support for nested objects right now. Unlike regular Mongo data modelling, using top level objects seems preferable in Meteor for most relationships, because that makes it much easier to deal with subscriptions and authorization for example. But there are use cases for nested objects, so if I have a need for it I might add it later.

Note that you can map value objects like dictionaries and arrays to nested JSON structures, if you set the type to 'Transformable' in the managed object model. I use this to map the 'profile' named values in the 'users' collection for example.

**Comment by trevorbroad** [comment]
That makes sense as to why I was having issues, thanks
