### ISSUE TITLE
Server configuration to set up websocket

### ISSUE THREAD

**Issue by Goatic** [martijnwalraven/meteor-ios#56]
I'm curious - how did you open the websocket for the ios app? I can't find any documentation on it anywhere in your readme :( How do I configure my server and get the appropriate URL for my mobile-app

**Comment by bitterloa** [comment]
not sure if this is helpful for you but this code is working for me in development to connect my app to my localhost dev meteor server (this is in my AppDelegate.swift file):

```
let mainConnectionURL = "ws://localhost:3000/websocket"
let Meteor = METCoreDataDDPClient(serverURL: NSURL(string: mainConnectionURL)!)

...
// And then further down in class AppDelegate

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        
        Meteor.connect()

```

What's important to note here is that I'm connecting with protocol `ws://` for insecure websockets -- in the example Todo app he is connecting using *secure* connection `"wss://meteor-ios-todos.meteor.com/websocket"` << please note that `ws://` is for when you aren't using SSL (like on a localhost dev machine) whereas using `wss://` with the extra "s" tries to use a secure connection, so you'd have to have SSL setup on the connecting server. Hope this helps

**Comment by Goatic** [comment]
Thanks for the advice :)

**Comment by Abhisheksnapwiz** [comment]
when ever i am trying to connect to my local running server using simulator i am not able to connect. 
for connection i am using "ws://MyLocalIP:4000:/websocket" url. please give me some solution.
when i am using direct url it is working but there is one issue is that some times it connecting and some times it getting crash by saying this reason: 'Attempting to send message without an open connection'
how to handle this crash?  because meteor-ios framework always checking for web socket is open or not to send message and if it found that web socket is not open then it is getting crash while sending message in this method of this line.
inside - (void)sendMessage:(NSDictionary *)message { getting crash at this line NSAssert(self.open, @"Attempting to send message without an open connection")

Please give some solution as soon as possible.
Thanks
